// Fetches stats.json — the same git-log-derived velocity data whatever.html's Velocity
// section inlines, regenerated by scripts/gen-stats.mjs on every commit (see its pre-commit
// hook). Cached after the first successful load since the file doesn't change mid-session.
let cached = null;
let pending = null;

export function loadStats() {
  if (cached) return Promise.resolve(cached);
  if (pending) return pending;
  pending = fetch('stats.json')
    .then(res => {
      if (!res.ok) throw new Error(`stats.json: HTTP ${res.status}`);
      return res.json();
    })
    .then(data => { cached = data; return data; })
    .finally(() => { pending = null; });
  return pending;
}
